version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodb_data:/data/db
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  go-app:
    build:
      context: ./go
      dockerfile: Dockerfile
    container_name: go-app-container
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app-network

  web-app:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web-app-container
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - go-app

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: