version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodb_data:/data/db
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]

  go-app:
    build:
      context: ./go
      dockerfile: Dockerfile
    container_name: go-app-container
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - GIN_MODE=debug

  web-app:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web-app-container
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - go-app
    environment:
      - API_URL=http://localhost:8080

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: